In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
from fungiclef.dataset import ImageMetadataDataset, EmbeddingMetadataDataset
from fungiclef.wrapper import FungiMetadataModule, FungiDinoModule
from fungiclef.transforms import get_transforms
import pandas as pd

# from torch.utils.data import DataLoader
# import lightning as L
# import torch
# from fungiclef.loss import FungiModelLoss, SeesawLoss
# import timm

# from lightning.pytorch.callbacks import ModelCheckpoint
# from lightning.pytorch.loggers import WandbLogger
# from torchvision.transforms import v2
# from torch.utils.data import default_collate
# from fungiclef.model import FungiMetadataModel, NUM_CLASSES, FungiMEEModel
# from lightning.pytorch.callbacks import LearningRateMonitor

# from torch.utils.data import DataLoader, WeightedRandomSampler

# import random

In [4]:
_train = pd.read_parquet('../train.pq')
_val = pd.read_parquet("../val.pq")

In [5]:
emb = pd.read_parquet("../dinov2_1024r.pq")

In [6]:
_val['embedding'] = list(emb.set_index('image_path').loc[_val['image_path']]['embedding'])

In [7]:
_train['embedding'] = list(emb.set_index('image_path').loc[_train['image_path']]['embedding'])

In [8]:
_train.to_parquet('../train1.pq')
_val.to_parquet('../val1.pq')

In [27]:
_train.to_parquet('../train1.pq', index=False)

In [ ]:
_train = pd.read_parquet('../train1.pq')
_val = pd.read_parquet("../val1.pq")

In [ ]:
_new_val = _train[_train.image_path.apply(lambda x: x[1] == '-')]
_new_train = _train[_train.image_path.apply(lambda x: x[1] != '-')]

In [ ]:
_new_train = pd.concat((_new_train, _val))

In [28]:
_new_train.to_parquet('../train2.pq', index=False)

In [29]:
_new_val.to_parquet('../val2.pq', index=False)

In [30]:
pd.read_parquet('../train1.pq')

,observation_id,image_path,m0,m1,d0,d1,g0,g1,g2,g3,...,habitat_26,habitat_27,habitat_28,habitat_29,habitat_30,habitat_31,class_id,poisonous,unknown,embedding
0,2238546328,2238546328-30620.JPG,1.000000,6.123234e-17,0.101168,-0.994869,0.12500,0.62500,0.25000,0.18750,...,0,0,0,0,0,0,1273,0,0,"[0.7914892, 0.49164742, -0.04174125, -0.491612..."
1,2558871973,2558871973-53941.JPG,0.000000,1.000000e+00,0.394356,0.918958,0.09375,0.31250,0.78125,0.31250,...,0,0,0,0,0,0,708,0,0,"[-0.291337, 1.1796793, -0.7607818, -1.4084797,..."
2,2238503501,2238503501-245559.JPG,-0.500000,-8.660254e-01,-0.897805,-0.440394,0.12500,0.62500,0.75000,0.15625,...,0,0,0,0,0,0,535,0,0,"[-1.5918314, -3.1277292, -2.5136974, 0.3732709..."
3,2446759075,2446759075-197643.JPG,-1.000000,-1.836970e-16,-0.937752,0.347305,0.09375,0.31250,0.62500,0.71875,...,0,0,0,0,0,0,832,0,0,"[0.9202639, 0.8228514, 0.16566564, 2.172102, 1..."
4,2238472345,2238472345-167057.JPG,-0.500000,-8.660254e-01,-0.790776,-0.612106,0.03125,0.84375,0.84375,0.15625,...,0,0,0,0,0,0,1338,0,0,"[-0.19837576, 0.75899214, -1.7788113, -2.93407..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325490,3380887400,0-3380887400.JPG,-0.866025,-5.000000e-01,-0.571268,0.820763,0.09375,0.43750,0.28125,0.40625,...,0,0,0,0,0,0,1716,0,1,"[-0.85892564, -0.09398366, -2.2680848, -0.7226..."
325491,3380887439,0-3380887439.JPG,-1.000000,-1.836970e-16,0.000000,1.000000,0.09375,0.43750,0.28125,0.40625,...,0,0,0,0,0,0,1716,0,1,"[-1.6275803, -1.4582856, -2.937529, 0.9729636,..."
325492,3382561357,0-3382561357.JPG,-1.000000,-1.836970e-16,0.571268,0.820763,0.09375,0.31250,0.40625,0.21875,...,0,0,0,0,0,0,1716,0,1,"[0.5762667, 0.8247456, -3.9262657, 0.63466185,..."
325493,3382561400,0-3382561400.JPG,-1.000000,-1.836970e-16,0.571268,0.820763,0.09375,0.31250,0.15625,0.81250,...,0,0,0,0,0,0,1716,0,1,"[-2.084352, -0.14438018, -3.0184333, -1.690277..."
325494,3399799331,0-3399799331.JPG,-0.866025,5.000000e-01,0.201299,0.979530,0.68750,0.96875,0.71875,0.87500,...,0,0,0,0,0,0,1716,0,1,"[1.2917815, -0.47033945, 0.063099615, 1.625365..."

In [31]:
pd.read_parquet('../train2.pq')

,observation_id,image_path,m0,m1,d0,d1,g0,g1,g2,g3,...,habitat_26,habitat_27,habitat_28,habitat_29,habitat_30,habitat_31,class_id,poisonous,unknown,embedding
0,2238546328,2238546328-30620.JPG,1.000000e+00,6.123234e-17,0.101168,-0.994869,0.12500,0.62500,0.25000,0.18750,...,0,0,0,0,0,0,1273,0,0,"[0.005949932, 0.1469564, -0.49620047, -0.11075..."
1,2558871973,2558871973-53941.JPG,0.000000e+00,1.000000e+00,0.394356,0.918958,0.09375,0.31250,0.78125,0.31250,...,0,0,0,0,0,0,708,0,0,"[-0.65260863, -0.0013587554, 0.5044832, -1.605..."
2,2238503501,2238503501-245559.JPG,-5.000000e-01,-8.660254e-01,-0.897805,-0.440394,0.12500,0.62500,0.75000,0.15625,...,0,0,0,0,0,0,535,0,0,"[0.5572929, 0.28234318, 0.15551983, 0.96624637..."
3,2446759075,2446759075-197643.JPG,-1.000000e+00,-1.836970e-16,-0.937752,0.347305,0.09375,0.31250,0.62500,0.71875,...,0,0,0,0,0,0,832,0,0,"[-0.017160544, -1.2300191, -0.3357499, 1.29131..."
4,2238472345,2238472345-167057.JPG,-5.000000e-01,-8.660254e-01,-0.790776,-0.612106,0.03125,0.84375,0.84375,0.15625,...,0,0,0,0,0,0,1338,0,0,"[0.3639089, 0.3726992, 0.7560097, 1.3864249, 0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325388,3329724347,0-3329724347.JPG,1.224647e-16,-1.000000e+00,-0.201299,0.979530,0.09375,0.25000,0.71875,0.37500,...,0,0,0,0,0,0,931,0,0,"[-0.419278, 0.66633576, -0.14421214, -1.171455..."
325389,3386484353,1-3386484353.JPG,-1.000000e+00,-1.836970e-16,0.790776,-0.612106,0.09375,0.31250,0.93750,0.06250,...,0,0,0,0,0,0,354,0,0,"[0.20411424, 0.07578691, 0.085911274, 0.406758..."
325390,3358360476,0-3358360476.JPG,-8.660254e-01,-5.000000e-01,-0.937752,0.347305,0.03125,0.93750,0.37500,0.62500,...,0,0,0,0,0,0,1047,0,0,"[-0.56015354, -0.18738864, -0.25037435, -0.242..."
325391,3313857314,0-3313857314.JPG,5.000000e-01,-8.660254e-01,-0.571268,0.820763,0.09375,0.25000,0.90625,0.81250,...,0,0,0,0,0,0,494,0,0,"[-0.24733329, 0.13334583, 1.0067952, -0.394908..."
325392,3358362501,1-3358362501.JPG,-8.660254e-01,-5.000000e-01,-0.988468,0.151428,0.03125,0.93750,0.68750,0.43750,...,0,0,0,0,0,0,46,0,0,"[0.5734333, -0.28166047, 0.24718498, 0.6510988..."

In [ ]:
# _train['class_id'] = _train.class_id.apply(lambda x: 1716 if x == -1 else x)
# _val['class_id'] = _val.class_id.apply(lambda x: 1716 if x == -1 else x)


# _train['unknown'] = _train.class_id.apply(lambda x: 1 if x > 1603 else 0)
# _val['unknown'] = _val.class_id.apply(lambda x: 1 if x > 1603 else 0)

In [ ]:
# _train.to_csv('../train.csv')
# _val.to_csv('../val.csv')

In [ ]:
# poison_mapping = {}
# for _, row in _train[['class_id', 'poisonous']].iterrows():
    
#     class_id = row['class_id']
#     poison = row['poisonous']
#     if poison_mapping.get(class_id):
#         if poison_mapping[class_id] != poison:
#             print(class_id)
    
#     poison_mapping[class_id] = poison

In [ ]:
train_df = pd.read_parquet('../train.pq')
val_df = pd.read_parquet("../val.pq")

# _val.unknown.sum() / len(_val)

In [ ]:
train_dataset = EmbeddingMetadataDataset(
    train_df,
)

In [ ]:

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    sampler=sampler,
    num_workers=WORKERS,
)

In [ ]:
emb, _, _, = next(iter(train_loader))

In [ ]:
emb.shape

torch.Size([512, 1024])

In [ ]:
_train.class_id.value_counts().sort_index()

class_id
0        343
1        215
2         63
3         45
4        535
        ...
1712      21
1713      21
1714      20
1715      21
1716    5247
Name: count, Length: 1717, dtype: int64

In [ ]:
_val['class_id'] = _val.class_id.apply(lambda x: 1716 if x == -1 else x)

In [ ]:
import numpy as np

In [ ]:
from scipy.stats import entropy

In [ ]:
train_dist = np.array([_train.class_id.value_counts().get(i, 1) for i in range(1717)])
val_dist = np.array([_val.class_id.value_counts().get(i, 1) for i in range(1717)])

In [ ]:
train_dist = train_dist / train_dist.sum()
val_dist = val_dist / val_dist.sum()

In [ ]:
entropy(val_dist, train_dist)

0.8182922920968481

In [ ]:
dist_weights = val_dist / train_dist

In [ ]:
_train_weights = [dist_weights[class_id] for class_id in _train['class_id']]

In [ ]:
# we want weighted random sampling WITH replacement to reach the desired distribution

sample = list(WeightedRandomSampler(_train_weights, 100000, replacement=True))

In [ ]:
from fungiclef.model import FungiMEEModel

train_loader = DataLoader(
    train_dataset,
    batch_size=67,
)
model = FungiMEEModel(num_classes=1719)

/home/chris/miniconda3/envs/fungiclef/lib/python3.11/site-packages/torch/nn/modules/transformer.py:286: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")

In [ ]:
emb, metadata, y_cls = next(iter(train_loader))

In [ ]:
o = model.forward(emb, metadata)

In [ ]:
o.shape

torch.Size([67, 1719])

In [ ]:

# Weighted sampling
train_dist = np.array([train_df.class_id.value_counts().get(i, 1) for i in range(NUM_CLASSES)])
val_dist = np.array([val_df.class_id.value_counts().get(i, 1) for i in range(NUM_CLASSES)])

train_dist = train_dist / train_dist.sum()
val_dist = val_dist / val_dist.sum()

dist_weights = val_dist / train_dist

_train_weights = [dist_weights[class_id] for class_id in train_df['class_id']]

sampler = WeightedRandomSampler(_train_weights, len(_train_weights), replacement=True)

In [ ]:
BATCH_SIZE=1024
WORKERS = 4

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    sampler=sampler,
    num_workers=WORKERS,
)

In [ ]:
emb, metadata, y_cls = next(iter(train_loader))

In [ ]:
y_pred = model.forward(emb, metadata)

In [ ]:
y_pred.shape

torch.Size([16, 1719])

In [ ]:
y_pred_cls = y_pred[:, :NUM_CLASSES]
y_pred_poison = y_pred[:, :-2]
y_pred_unknown = y_pred[:, :-1]

In [ ]:

# Class distribution for seesaw / CE loss
class_distribution = []
c = val_df.class_id.value_counts()
for i in range(NUM_CLASSES):
    class_distribution.append(c.get(i, 1))

# Try use focal loss
# loss = FungiModelLoss(loss="cross_entropy", class_distribution=class_distribution)
loss = SeesawLoss(
    class_distribution=torch.Tensor(class_distribution), num_classes=NUM_CLASSES
)

In [ ]:
loss.forward(y_pred_cls, y_cls)

tensor(6.4440, grad_fn=<NllLossBackward0>)

In [ ]:
train_df.keys()

Index(['observation_id', 'image_path', 'm0', 'm1', 'd0', 'd1', 'g0', 'g1',
       'g2', 'g3', 'g4', 'g5', 'g_float', 'substrate_0', 'substrate_1',
       'substrate_2', 'substrate_3', 'substrate_4', 'substrate_5',
       'substrate_6', 'substrate_7', 'substrate_8', 'substrate_9',
       'substrate_10', 'substrate_11', 'substrate_12', 'substrate_13',
       'substrate_14', 'substrate_15', 'substrate_16', 'substrate_17',
       'substrate_18', 'substrate_19', 'substrate_20', 'substrate_21',
       'substrate_22', 'substrate_23', 'substrate_24', 'substrate_25',
       'substrate_26', 'substrate_27', 'substrate_28', 'substrate_29',
       'substrate_30', 'metasubstrate_0', 'metasubstrate_1', 'metasubstrate_2',
       'metasubstrate_3', 'metasubstrate_4', 'metasubstrate_5',
       'metasubstrate_6', 'metasubstrate_7', 'metasubstrate_8',
       'metasubstrate_9', 'habitat_0', 'habitat_1', 'habitat_2', 'habitat_3',
       'habitat_4', 'habitat_5', 'habitat_6', 'habitat_7', 'habitat_8',
       'habitat_9', 'habitat_10', 'habitat_11', 'habitat_12', 'habitat_13',
       'habitat_14', 'habitat_15', 'habitat_16', 'habitat_17', 'habitat_18',
       'habitat_19', 'habitat_20', 'habitat_21', 'habitat_22', 'habitat_23',
       'habitat_24', 'habitat_25', 'habitat_26', 'habitat_27', 'habitat_28',
       'habitat_29', 'habitat_30', 'habitat_31', 'class_id', 'poisonous',
       'unknown', 'embedding'],
      dtype='object')

In [ ]:
module = FungiDinoModule(model)
module.training_step(next(iter(train_loader)), 0)

torch.Size([512, 1717])
torch.Size([512])
8.39221477508545 1.931061029434204 2.664058208465576

tensor(12.9873, grad_fn=<AddBackward0>)

In [ ]:
module.validation_step(next(iter(train_loader)), 0)

8.081535339355469 0.9779545068740845 2.3785622119903564
tensor([0.0771])

/home/chris/miniconda3/envs/fungiclef/lib/python3.11/site-packages/lightning/pytorch/core/module.py:436: You are trying to `self.log()` but the `self.trainer` reference is not registered on the model yet. This is most likely because the model hasn't been passed to the `Trainer`

In [ ]:
module.train_unknown_auc.compute()

tensor([0.4207])

In [ ]:
y_pred_unknown.dtype

torch.float32

In [ ]:
module = FungiDinoModule(model)

In [ ]:
trainer = L.Trainer()

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

In [ ]:
trainer.fit(module, train_loader)

/home/chris/miniconda3/envs/fungiclef/lib/python3.11/site-packages/lightning/pytorch/trainer/configuration_validator.py:74: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/home/chris/miniconda3/envs/fungiclef/lib/python3.11/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:441: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.

Finding best initial lr:   0%|          | 0/100 [00:00<?, ?it/s]

AttributeError: 'CosineAnnealingWarmRestarts' object has no attribute 'lr'

In [ ]:

from lightning.pytorch.tuner import Tuner
tuner = Tuner(trainer)

In [ ]:
tuner.lr_find(module, train_loader)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Finding best initial lr:   0%|          | 0/100 [00:00<?, ?it/s]

8.486292839050293 1.9627984762191772 4.412660598754883
8.339370727539062 1.973696231842041 4.249325275421143
8.355053901672363 1.8620564937591553 4.159492492675781
8.421277046203613 2.0425992012023926 2.547520160675049
8.410826683044434 2.0301833152770996 4.4618682861328125
8.36603832244873 1.8691387176513672 3.223252534866333
8.332356452941895 2.077699661254883 4.626202583312988
8.518049240112305 1.9866005182266235 5.0313520431518555
8.3772611618042 1.9346709251403809 4.192398548126221
8.422147750854492 1.8675293922424316 2.9905166625976562
8.359295845031738 1.9520699977874756 4.790858745574951
8.395316123962402 1.991556167602539 3.487802743911743
8.471059799194336 2.004399538040161 5.562211036682129
8.430899620056152 1.8257172107696533 4.140017509460449
8.42017936706543 1.9030178785324097 4.741320610046387
8.345921516418457 1.911820888519287 4.348722457885742
8.40463638305664 1.9026134014129639 3.9237890243530273
8.382379531860352 1.936704158782959 4.166499137878418
8.38357162475586 1.9524288177490234 4.278994560241699
8.404399871826172 1.8542572259902954 3.6790413856506348
8.41799545288086 2.0974245071411133 4.070157527923584
8.361172676086426 1.9431120157241821 5.935688495635986
8.433424949645996 1.9297354221343994 3.3123369216918945
8.368927001953125 1.9299222230911255 4.31889533996582
8.463897705078125 1.975383996963501 5.020276069641113
8.478462219238281 1.989440679550171 5.037417411804199
8.419510841369629 1.994694709777832 3.6131014823913574
8.398038864135742 1.9370231628417969 3.9118478298187256
8.387453079223633 1.9301605224609375 4.4966583251953125
8.393664360046387 1.8468725681304932 5.092843532562256
8.438826560974121 1.879455804824829 3.1627392768859863
8.381070137023926 1.875170111656189 3.4295802116394043
8.420331954956055 1.943571925163269 3.516916036605835
8.409489631652832 1.729142665863037 3.6455435752868652
8.403583526611328 1.936274528503418 3.602257251739502
8.327014923095703 1.9184908866882324 3.125579357147217
8.284809112548828 1.8916916847229004 2.5372653007507324
8.339410781860352 1.7258388996124268 3.8210387229919434
8.326894760131836 1.7984473705291748 2.95745849609375
8.368670463562012 1.819665789604187 3.5657777786254883
8.273836135864258 1.720965027809143 2.595322370529175
8.18836498260498 1.715522289276123 2.8616929054260254
8.201120376586914 1.7326765060424805 1.88311767578125
8.013904571533203 1.619715690612793 2.6938397884368896
7.987607955932617 1.7228055000305176 1.886500597000122
8.033045768737793 1.5912621021270752 2.1369223594665527
7.890252113342285 1.643554925918579 2.1810684204101562
7.781978607177734 1.6096047163009644 2.0174577236175537
7.595881462097168 1.4983946084976196 1.8059630393981934
7.464735507965088 1.5257370471954346 1.8306750059127808
7.289234638214111 1.5147948265075684 1.8966519832611084
7.049119472503662 1.515425682067871 2.0810651779174805
6.780402660369873 1.454438328742981 1.9140665531158447
6.334662437438965 1.414947509765625 2.321197509765625
6.170489311218262 1.5693466663360596 1.7442278861999512
5.812742710113525 1.5400079488754272 1.6159498691558838
5.4749627113342285 1.468629002571106 1.9420802593231201
5.231152057647705 1.424574851989746 1.7568879127502441
5.277417182922363 1.5388591289520264 1.6876519918441772
5.004291534423828 1.4163225889205933 1.4043480157852173
4.631204605102539 1.367202639579773 3.3033080101013184
4.393345355987549 1.4057451486587524 2.471050262451172
4.3412089347839355 1.4069125652313232 1.8582050800323486
4.425047397613525 1.4089276790618896 2.4629087448120117
4.38361120223999 1.3106416463851929 2.1177163124084473
4.2401299476623535 1.2626643180847168 2.096917152404785
3.9453976154327393 1.2150193452835083 1.5164141654968262
3.737764358520508 1.2756177186965942 1.7975835800170898
3.6802051067352295 1.3815817832946777 2.053102493286133
3.4012293815612793 1.1544437408447266 1.3437588214874268
3.64258074760437 1.1598162651062012 1.4942500591278076
3.445667266845703 1.1665089130401611 1.6328486204147339
3.53483247756958 1.234218955039978 1.6383150815963745
3.7618942260742188 1.1601762771606445 1.406170129776001
3.767223596572876 1.153199553489685 1.2080212831497192
3.8163936138153076 1.2407805919647217 1.1882917881011963
3.8781909942626953 1.2262705564498901 1.4223278760910034
3.7639544010162354 1.1835379600524902 1.4121676683425903
3.8753933906555176 1.2178034782409668 1.2672953605651855
3.9733920097351074 1.2152254581451416 1.3957138061523438
3.8827829360961914 1.188079833984375 1.1601519584655762
3.9455654621124268 1.2061080932617188 1.5860439538955688
4.061562538146973 1.3812817335128784 1.694450855255127
3.9468860626220703 1.2537519931793213 1.304636001586914
3.842804193496704 1.2837263345718384 1.7524070739746094
3.707146644592285 1.187288522720337 1.6277334690093994
3.699288845062256 1.2044808864593506 1.502837896347046
3.381334066390991 1.1582539081573486 1.1963551044464111
3.5638322830200195 1.125915765762329 1.6377774477005005
4.14274787902832 1.258007287979126 2.1187870502471924
5.572473049163818 3.0175423622131348 3.224947929382324
12.67340087890625 8.280447006225586 3.5820207595825195
9.596465110778809 7.9208879470825195 5.654219627380371
18.84894561767578 16.71161651611328 13.852115631103516
60.76251983642578 49.76417922973633 23.711448669433594
124.65257263183594 219.24038696289062 59.3005256652832

LR finder stopped early after 97 steps due to diverging loss.
Learning rate set to 0.003981071705534969
Restoring states from the checkpoint path at /home/chris/fungiclef-2024/scripts/.lr_find_5117143b-c9e5-4e52-aeaa-0da34fe88431.ckpt
Restored all states from the checkpoint at /home/chris/fungiclef-2024/scripts/.lr_find_5117143b-c9e5-4e52-aeaa-0da34fe88431.ckpt

401.7701110839844 205.01028442382812 451.8348388671875

In [ ]:
trainer.callbacks

[<lightning.pytorch.callbacks.lr_finder.LearningRateFinder at 0x7fadcd201850>,
 <lightning.pytorch.callbacks.progress.tqdm_progress.TQDMProgressBar at 0x7fadf7e37550>,
 <lightning.pytorch.callbacks.model_summary.ModelSummary at 0x7fb232765cd0>,
 <lightning.pytorch.callbacks.model_checkpoint.ModelCheckpoint at 0x7fadf83ea410>]